### PR TITLE
Hindi translations updated

### PR DESCRIPTION
**Pull request by Premjit-Chowdhury**

### CODE REVIEW

**Comment by itsaky** [comment]
Could you please translate other modules too? Especially `:lsp:java`.

**Comment by Premjit-Chowdhury** [comment]
> Could you please translate other modules too? Especially `:lsp:java`.

ok , i will translate it too.
please also tell other module names except lsp.

**Comment by itsaky** [comment]
You can always generate the translation report and check which translations are missing/orphan etc.

Use the `:app:checkTranslations` task to generate the report.

**Comment by Premjit-Chowdhury** [comment]
> You can always generate the translation report and check which translations are missing/orphan etc.
> 
> Use the `:app:checkTranslations` task to generate the report.

Most of the modules translated except lsp so i wll update it too.

**Comment by Premjit-Chowdhury** [comment]
lsp java folder strings now translated to hindi.
But where would i use this gradle task `:app:checkTranslations` command? Because in Tasks there is no option for that.

**Comment by itsaky** [comment]
Try to execute `bash gradlew :app:checkTranslations` in terminal.

**Comment by Premjit-Chowdhury** [comment]
You can now merge this PR. I checked everything is up-to-date from my side.

**Comment by itsaky** [comment]
Thank you for your contribution!

**Pull request merged**
