### PR TITLE
Improved translation into Russian

### PR DESCRIPTION
**Pull request by AndreyKozhev**
Improved translation into Russian in modules app, emulatorview, common, lsp/xml, xml-inflater

### CODE REVIEW

**Comment by itsaky** [comment]
Thanks. I'll review this soon.

**Comment by AndreyKozhev** [comment]
Ok

**Comment by NikkaGames** [comment]
@AndreyKozhev 🫠

**Comment by NikkaGames** [comment]
@NikkaGames xd

**Review by MrIkso — APPROVED** [review]

**Comment by itsaky** [comment]
Should we expect any more changes in this?

If you're going to edit other translations as well, please mark this PR as draft. When you're sure that no more edits are required, mark the PR as ready.

**Comment by AndreyKozhev** [comment]
Okay.
I don't plan to make edits yetю

**Review by MrIkso — APPROVED** [review]

**Comment by itsaky** [comment]
@MrIkso Thanks for the review.
@AndreyKozhev Thank you for the contribution.

**Pull request merged**
