### PR TITLE
Adding libgdx template project

### PR DESCRIPTION
**Pull request by Smooth-E**
<h1 align="center">Introduction</h1>
As a solution to #14, here I included a LibGDX template project. Compile-ability of this tested and seems to work well.
Output of this template will display an image to a screen.

<h1 align="center">Proof of compile-abilty</h1>
<table border=0 cellspacing=0 cellpadding=0>
<tr>
<td>

</td>
<td>

</td>
<td>

</td>
</tr>
</table>
<h1 align="center">Output project</h1>
<p align="center">

</p>

# Notes
This is my first ever pull request, if you will find any mistakes or issues in it, feel free to tell me.

### CODE REVIEW

**Comment by itsaky** [comment]
@Smooth-E
The template can not be built because Gradle 7.0.2 does not support JDK 17 (it builds successfully with JDK 11). When building with JDK 17, the build fails with the message : `Unrecognized VM option 'MaxPermSize=1G' `.

The option was [removed in OpenJDK 17](https://docs.oracle.com/en/java/javase/17/docs/specs/man/java.html#removed-java-options).

I cloned and built the project template from [your template repository](https://github.com/Smooth-E/libgdx-template-for-android-ide).

**Comment by Smooth-E** [comment]
>  Gradle 7.0.2 does not support JDK 17 

You said [here](https://t.me/androidide_discussions/17659) that Gradle 7.0.2 is a good one and is fully supported by IDE (or maybe I misunderstood). Which Gradle version should I use then?

I will also upgrade this project to the latest version of libgdx (1.10.0) and commit changes soon.

**Comment by itsaky** [comment]
In that message, I was talking about `Android Gradle Plugin` version and not `Gradle distribution` version. You'll need to change the `distributionUrl` in `gradle-wrapper.properties` to use Gradle 7.3.

**Comment by Smooth-E** [comment]
Done! Updated url to gradle binary and changed libgdx version to 1.10.0. Note that [they dropped armeabi support since this version](https://libgdx.com/news/2021/04/the-ultimate-migration-guide#:~:text=%5B1.10.0%5D%20Android%20ARMv5%20(armeabi)%20support%20has%20been%20dropped.%20Remove%20any%20dependency%20with%20the%20natives%2Darmeabi%20qualifier%20(but%20not%20natives%2Darmeabi%2Dv7a!)%20from%20your%20gradle%20build%20files.%20This%20applies%20to%20gdx%2Dplatform%2C%20gdx%2Dbullet%2Dplatform%2C%20gdx%2Dfreetype%2Dplatform%20and%20gdx%2Dbox2d%2Dplatform.). Also updated [my template repository](https://github.com/Smooth-E/libgdx-template-for-android-ide), so it is now up-to-date with a project included [here](https://github.com/Smooth-E/AndroidIDE/blob/adding-libgdx-template-project/app/src/main/assets/templates/4.zip).

**Pull request merged**
