### PR TITLE
Add new Login Activity project template with Java and Kotlin support

### PR DESCRIPTION
**Pull request by MatheusTGamerPro**
This is a basic login screen template, which contains a file called **LoginActivity** where is an activity that will have the login layout, also implement some empty functions for the user can implement in the login system, the functions are:

- **Login**
-  **Register**
- **isSaveLogin**

These functions are empty, they are only created in code.Here are some pictures of what the model looks like: 

login_activity_screen_1
login_activity_screen_2

When the Login Screen button is pressed, the user is redirected to the login screen, where the programmer (user) can edit and do whatever he wants.

### CODE REVIEW

**Comment by MatheusTGamerPro** [comment]
I just didn't make the interface more stylized, because it would make the model too big, but if you prefer, I can improve the design.

**Comment by MrIkso** [comment]
1. Your template not originally form Android Studio
2. Your template icon not good, use normal from [here](https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:wizard/template-impl/res/login-fragment/template_login_fragment.png) 
3. And why a sense from this? I don't added it, since this does not make sense, you can write the project you need yourself.

**Comment by MatheusTGamerPro** [comment]
> 1. Your template not originally form Android Studio
> 2. Your template icon not good, use normal from [here](https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:wizard/template-impl/res/login-activity/template_login_activity.png)
> 3. And why a sense from this? I don't added it, since this does not make sense, you can write the project you need yourself.

1. I didn't put identical to Android to make something different and unique

2. Ok..

3. The reason is basic, many users and programmers nowadays use a login system in their applications, a login activity would advance one of the layout creation processes, it is enough that the user Modify the interface (if desired) as he sees fit.

**Comment by MatheusTGamerPro** [comment]
This is how the template was in the app

**Comment by itsaky** [comment]
Could you improve the UI of the template app? Maybe use material components.

**Comment by MatheusTGamerPro** [comment]
> Could you improve the UI of the template app? Maybe use material components.

OK

**Comment by QiubyZ** [comment]
why doesn't anyone think of making the Load template feature, instead of having to be like that...

**Comment by MatheusTGamerPro** [comment]
> why doesn't anyone think of making the Load template feature, instead of having to be like that...
> it's just like creating a project as usual, which will be changed only Package Name, minsdk and maxsdk.
> 
> it's better, because we can customize gradle build directly. and will only be loaded on the selection of the "Load Template" feature.
> 

perhaps, it's not a bad idea.

**Comment by MatheusTGamerPro** [comment]
this is the "RegisterActivity", I added the "LoginActivity" and this activity is below
Screenshot_2022-07-12-03-49-11-006_com yourpackage loginactivity

**Comment by QiubyZ** [comment]
@MatheusTGamerPro It is better. because everyone can create their own project template. Instead of having to wait for developer updates that won't necessarily be approved

**Comment by MatheusTGamerPro** [comment]
This is the New Design, using Material Components and gradient coloring, the first is the Login screen, and the second is the register screen.

- Login Screen
Screenshot_2022-07-12-16-13-28-389_com yourpackage loginacticity2
- Register Screen
Screenshot_2022-07-12-16-15-57-104_com yourpackage loginactivity

**Comment by MatheusTGamerPro** [comment]
This PR is already successfully completed, and the template has also been tested.

**Comment by TimScriptov** [comment]
Terrible pattern

**Comment by TimScriptov** [comment]
It doesn't need

**Comment by datechies** [comment]
@MatheusTGamerPro I don't think it require

**Comment by MrIkso** [comment]
I'm added feature to use import your templatees. We don't need this template

**Comment by MatheusTGamerPro** [comment]
ok then i will close this PR

**Pull request closed without merging**
