### PR TITLE
Add a new Flashlight Template

### PR DESCRIPTION
**Pull request by MatheusTGamerPro**
With this template it is possible to create a basic system to turn the flashlight on and off (same as the Android Studio template).

### CODE REVIEW

**Comment by MatheusTGamerPro** [comment]
I intend to also add Login Activity and Settings Screen , and put Kotlin support if possible at all.

**Review by MatheusTGamerPro — COMMENTED** [review]
This file has nothing changed, it was just a test (just ignore it)

**Comment by itsaky** [comment]
I'm not sure if a flashlight template should be included or not.

> I intend to also add Login Activity and Settings Screen , and put Kotlin support if possible at all.

We could definitely include a login or settings screen.

**Comment by MatheusTGamerPro** [comment]
> I'm not sure if a flashlight template should be included or not.
> 
> > I intend to also add Login Activity and Settings Screen , and put Kotlin support if possible at all.
> 
> We could definitely include a login or settings screen.

Ok, the login I'm already building, I'll open a new pull request when I finish it

**Comment by MatheusTGamerPro** [comment]
the login activity template is ready(Java and Kotlin support), I will close this PR and open another one when I finish implementing it on GitHub.

**Pull request closed without merging**
