### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by Se-Lyan**

### CODE REVIEW

**Comment by MarvinStelter** [comment]
Please provide strings for other modules too, then I'll merge it.

**Comment by Se-Lyan** [comment]
which modules?

**Comment by MarvinStelter** [comment]
:common
:emulatorview
:xml-inflater
:lsp:java

Also check the build output here on GitHub, something is wrong with your strings file (build failed)

I guess Akash will merge it soon, if you fix everything

**Comment by Se-Lyan** [comment]
I had to delete something or add a character I'll check that

**Comment by Se-Lyan** [comment]
Trying again didn't work?

**Comment by Se-Lyan** [comment]
Because its work for me now

**Comment by BanDroid** [comment]
Your translations have syntax errors, please check it again.

**Comment by Se-Lyan** [comment]
Oh okay now i understand, i created a new fork, and it work

**Comment by Se-Lyan** [comment]
But the current fork its not the new

**Pull request closed without merging**
