### PR TITLE
Add Bengali translations

### PR DESCRIPTION
**Pull request by deepkrg17**
Added some strings.xml files for Bengali translation.

### CODE REVIEW

**Comment by codejoker01** [comment]
Please sign your commits. [Learn about signing commits.](https://docs.github.com/articles/about-gpg/)

**Review by codejoker01 — APPROVED** [review]

**Comment by deepkrg17** [comment]
I was not aware about signing commits. Today I have learnt about it and added GPG key.
But signing old commits , changes commit's hashes.
Wii not it a problem for this pull request?

**Comment by itsaky** [comment]
The translations are incomplete. Please provide complete translations.

**Comment by deepkrg17** [comment]
Completed.

**Comment by itsaky** [comment]
These two modules aren't translated :
- `:lsp:java`
- `:lsp:xml`

**Comment by deepkrg17** [comment]
Done, I think. If any problems are left, please reply.

**Review by itsaky — APPROVED** [review]

**Comment by itsaky** [comment]
Thanks for your contribution. Sorry for the delay.

**Pull request merged**
